### ISSUE TITLE
FreeIPMI command line options

### ISSUE THREAD

**Issue by chu11** [solarkennedy/ipmi-sel-comparison#1]
I'm the maintainer of FreeIPMI.  I came upon your blog post completely at random (http://www.xkyle.com/an-ipmi-sel-viewing-shootout/).  Just thought I'd mention a few things about FreeIPMI.

By default, FreeIPMI does not interpret OEM events.  There is a command line option to enable it, --interpret-oem-data.  If FreeIPMI currently supports that motherboard's OEM events, then SEL events will have more OEM info in them.  Not sure what motherboard you ran for these tests of course, but a list of supported ones are in the manpage.

Another option to try would be the workaround "-W assumesystemevent".  Short answer, some motherboards output illegal SEL record types.  Which you witnessed with "Unknown SEL Record Type: 3h" output.  FreeIPMI errs on the side of caution and does not output the SEL event, b/c FreeIPMI can't vouch for its correctness and the data in it.  It appears that ipmiutil and ipmitool go ahead and just make assumptions that it's the standard type of SEL record.  In this particular case, it appears their guess was correct (atleast comparing to the vendor software output).

**Comment by solarkennedy** [comment]
Whoa! Thanks for opening the issue!

I was not aware of the extra command line options for the FreeIPMI toolset. 

I'm surprised I didn't include the motherboard I was on! I'm pretty sure it was a Intel S5500 series, which looks like it is supported on the version I have in front of me.

I'll update the blog post with your followup! (and if I feel really ambitious, I'll re-run my suite with more up-to-date versions and your suggested options?)

**Comment by chu11** [comment]
No problem, glad to be of help.

**Comment by solarkennedy** [comment]
I've updated the blog with an update: http://www.xkyle.com/an-ipmi-sel-viewing-shootout/
